version: "3.1"

networks:
  tezda-network:
    driver: bridge

services:
  webserver:
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    container_name: tezda-webserver
    restart: unless-stopped
    tty: true
    ports:
      - '${DOCKER_APP_PORT:-80}:80'
      - '${DOCKER_FRONT_PORT:-5173}:5173'
      - '${DOCKER_SSL_PORT:-9017}:9016'
    expose:
      - "${DOCKER_APP_PORT:-80}"
      - "${DOCKER_SSL_PORT:-9017}"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/certs:/certs
    working_dir: /var/www/html
    depends_on:
      - appserver
    networks:
      - tezda-network

  appserver:
    build:
      context: .
      dockerfile: docker/php.dockerfile
    container_name: tezda-appserver
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    networks:
      - tezda-network

  mysql:
    build:
      context: .
      dockerfile: docker/mysql.dockerfile
    command: --default-authentication-plugin=mysql_native_password
    container_name: tezda-db
    restart: unless-stopped
    tty: true
    ports:
      - "${DOCKER_DB_PORT:-3366}:3306"
    expose:
      - "${DOCKER_DB_PORT:-3366}"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      #      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      #      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - tezda-network

  npm:
    image: node:18.10.0
    container_name: tezda-npm
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - tezda-network

  composer:
    build:
      context: .
      dockerfile: docker/composer.dockerfile
    container_name: tezda-composer
    volumes:
      - .:/var/www/html
      - ./docker/php-composer.ini:/usr/local/etc/php/conf.d/php-composer.ini
    networks:
      - tezda-network

volumes:
  mysql:
    driver: local
